services:
  postgres:
    image: postgres:14
    container_name: tlc_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:4.0.0-alpha-2
    container_name: tlc_hive-metastore
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_URIS: thrift://hive-metastore:9083
      METASTORE_DB_TYPE: postgres
      METASTORE_DB_HOST: postgres
      METASTORE_DB_NAME: metastore
      METASTORE_DB_USER: hive
      METASTORE_DB_PASSWORD: hive
    command: /opt/hive/bin/hive --service metastore

  trino:
    image: trinodb/trino:latest
    container_name: tlc_trino
    depends_on:
      - hive-metastore
    ports:
      - "8081:8080"
    volumes:
      - ./infra/trino_docker/trino-config:/etc/trino
      - ./infra/trino_docker/db:/data/warehouse

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: tlc_app
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TRINO_HOST=trino
      - TRINO_PORT=8080
    depends_on:
      - postgres
      - trino

  optimizer_service:
    build:
      context: .
      dockerfile: Dockerfile.optimizer
    container_name: tlc_optimizer_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TRINO_HOST=trino
      - TRINO_PORT=8080
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
    depends_on:
      - postgres
      - trino

volumes:
  postgres_data: